Repository Homebrew/homebrew-cask-drivers, pull requests merged in 2020-09, with the labels that each got.

#1754 Update logitech-control-center from 3.9.11 to 3.9.12
  Casks/logitech-control-center.rb
Labels: ci-skip-install

#1753 Update corsair-icue from 3.32.80 to 3.33.246
  Casks/corsair-icue.rb
Labels: ci-skip-appcast

#1772 huion-tablet: Add Cask
  Casks/huiontablet.rb
Labels: awaiting user reply

#1782 Update logitech-control-center
  Casks/logitech-control-center.rb
Labels: ci-skip-install
