Repository Homebrew/homebrew-cask-drivers, pull requests merged in 2020-11, with the labels that each got.

#1862 Update corsair-icue from 3.34.161 to 3.34.170
  Casks/corsair-icue.rb
Labels: ci-skip-appcast

#1891 Fix RuboCop offenses.
  Casks/behringer-x32-edit.rb
  Casks/interstuhl-s40.rb
  Casks/sound-blaster-play3.rb
  Casks/suunto-moveslink2.rb
Labels: ci-syntax-only

#1904 Bump drobo-dashboard to 3.5.2
  Casks/drobo-dashboard.rb
Labels: ci-skip-appcast

#1918 Update logitech-control-center from 3.9.12 to 3.9.14
  Casks/logitech-control-center.rb
Labels: ci-skip-install
