Repository Homebrew/homebrew-cask-drivers, pull requests merged in 2023-05, with the labels that each got.

#3438 philips-hue-sync 1.10.2.43
  Casks/philips-hue-sync.rb
Labels: bump-cask-pr

#3439 toneprint 4.5.10
  Casks/toneprint.rb
Labels: bump-cask-pr

#3440 logitune 3.1.109
  Casks/logitune.rb
Labels: bump-cask-pr

#3441 hdhomerun 20230503
  Casks/hdhomerun.rb
Labels: bump-cask-pr

#3442 synology-surveillance-station-client 2.1.1-2456
  Casks/synology-surveillance-station-client.rb
Labels: bump-cask-pr

#3444 Delete outdated casks.
  Casks/akai-professional-lpd8-editor.rb
  Casks/canon-eos-webcam-utility.rb
  Casks/canon-fax.rb
  Casks/canon-scangear-mf.rb
  Casks/content-manager-assistant.rb
  Casks/displaylink-login-extension.rb
  Casks/evoluent-vertical-mouse-device-controller.rb
  Casks/focusrite-control.rb
  Casks/lacie-network-assistant.rb
  Casks/logitech-control-center.rb
  Casks/logitech-firmwareupdatetool.rb
  Casks/logitech-gaming-software.rb
  Casks/logitech-unifying.rb
  Casks/luftdateninfo-flashing-tool.rb
  Casks/ni-488-2.rb
  Casks/nitrokey.rb
  Casks/pololu-avr-programmer-v2.rb
  Casks/shearwater.rb
  Casks/steelseries-exactmouse-tool.rb
  Casks/xbox360-controller-driver-unofficial.rb
  Casks/yubico-yubikey-personalization-gui.rb
  Casks/yubico-yubikey-piv-manager.rb
  Casks/zsa-wally.rb
Labels: automerge-skip, marked for removal/rejection

#3446 various: migrate casks
  Casks/logitune.rb
  Casks/obsbot-webcam.rb
  Casks/opal.rb
  tap_migrations.json
Labels: automerge-skip

#3447 tap_migrations: add pololu-avr-programmer-v2
  tap_migrations.json
Labels: automerge-skip

#3448 various: migrate casks
  Casks/creative.rb
  Casks/samsung-portable-ssd-t7.rb
  tap_migrations.json
Labels: automerge-skip

#3450 1kc-razer: add to tap-migrations
  tap_migrations.json
Labels: automerge-skip

#3452 caldigit-thunderbolt-charging: migrate to cask
  tap_migrations.json
Labels: automerge-skip

#3455 caldigit-docking-utility: migrate to cask
  tap_migrations.json
Labels: automerge-skip

#3456 asix-ax88179.rb is merging
  tap_migrations.json
Labels: automerge-skip

#3457 bose-updater: add to tap-migrations
  tap_migrations.json
Labels: automerge-skip

#3458 re-added shureplus-motiv
  tap_migrations.json
Labels: automerge-skip

#3459 Add pallotron-yubiswitch to tap_migrations.json
  tap_migrations.json
Labels: automerge-skip

#3460 tap_migrations: add konica-minolta-bizhub-c759-c658-c368-c287
  tap_migrations.json
Labels: automerge-skip

#3461 migrate zsa-wally
  tap_migrations.json
Labels: automerge-skip

#3463 tap_migrations: add hdhomerun
  tap_migrations.json
Labels: automerge-skip

#3466 tap_migrations: add tiptoi-manager
  tap_migrations.json
Labels: automerge-skip

#3464 tap_migrations: add insta360-studio
  tap_migrations.json
Labels: automerge-skip

#3468 Update tap_migrations.json with focusrite-control
  tap_migrations.json
Labels: automerge-skip

#3470 Add eobcanka to tap migrations
  tap_migrations.json
Labels: automerge-skip

#3471 tap_migrations: add synology products
  tap_migrations.json
Labels: automerge-skip

#3472 tab_migrations: add huiontablet
  tap_migrations.json
Labels: automerge-skip

#3473 tap_migrations.json: add `kiibohd-configurator`
  tap_migrations.json
Labels: automerge-skip

#3474 Migrate uhk-agent to homebrew-cask
  tap_migrations.json
Labels: automerge-skip
